export async function seed(knex) {
  // Get the demo user ID
  const demoUser = await knex('users')
    .where('email', 'demo@example.com')
    .first()
  const userId = demoUser?.id || null

  if (!userId) {
    console.warn('Demo user not found, skipping bill seeding')
    return
  }

  // Clear any existing bills
  await knex('bills').del()

  // Seed the bills table with data from the data.json file
  await knex('bills').insert([
    {
      avatar: '/assets/avatars/nimbus-data-storage.jpg',
      name: 'Nimbus Data Storage',
      category: 'Bills',
      date: new Date('2024-08-21T12:00:00Z'),
      amount: -9.99,
      dueDay: 21,
      isPaid: false,
      isOverdue: true,
      user_id: userId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      avatar: '/assets/avatars/bytewise.jpg',
      name: 'ByteWise',
      category: 'Bills',
      date: new Date('2024-08-23T14:30:00Z'),
      amount: -49.99,
      dueDay: 23,
      isPaid: false,
      isOverdue: true,
      user_id: userId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      avatar: '/assets/avatars/ecofuel-energy.jpg',
      name: 'EcoFuel Energy',
      category: 'Bills',
      date: new Date('2024-08-29T10:15:00Z'),
      amount: -35.0,
      dueDay: 29,
      isPaid: false,
      isOverdue: false,
      user_id: userId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      avatar: '/assets/avatars/premium-internet.jpg',
      name: 'Premium Internet Services',
      category: 'Bills',
      date: new Date('2024-08-12T09:00:00Z'),
      amount: -65.99,
      dueDay: 12,
      isPaid: false,
      isOverdue: true,
      user_id: userId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      avatar: '/assets/avatars/city-gym.jpg',
      name: 'City Gym & Fitness',
      category: 'Personal Care',
      date: new Date('2024-08-15T12:30:00Z'),
      amount: -42.5,
      dueDay: 15,
      isPaid: false,
      isOverdue: true,
      user_id: userId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      avatar: '/assets/avatars/harmony-music.jpg',
      name: 'Harmony Music Streaming',
      category: 'Entertainment',
      date: new Date('2024-08-17T15:45:00Z'),
      amount: -14.99,
      dueDay: 17,
      isPaid: false,
      isOverdue: true,
      user_id: userId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      avatar: '/assets/avatars/pixel-playground.jpg',
      name: 'Pixel Playground',
      category: 'Entertainment',
      date: new Date('2024-08-11T18:45:38Z'),
      amount: -10.0,
      dueDay: 11,
      isPaid: true,
      isOverdue: false,
      user_id: userId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      avatar: '/assets/avatars/spark-electric-solutions.jpg',
      name: 'Spark Electric Solutions',
      category: 'Bills',
      date: new Date('2024-08-02T09:25:11Z'),
      amount: -100.0,
      dueDay: 2,
      isPaid: true,
      isOverdue: false,
      user_id: userId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      avatar: '/assets/avatars/aqua-flow-utilities.jpg',
      name: 'Aqua Flow Utilities',
      category: 'Bills',
      date: new Date('2024-07-30T13:20:14Z'),
      amount: -50.0,
      dueDay: 30,
      isPaid: true,
      isOverdue: false,
      user_id: userId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      avatar: '/assets/avatars/serenity-spa-and-wellness.jpg',
      name: 'Serenity Spa & Wellness',
      category: 'Personal Care',
      date: new Date('2024-08-03T14:00:37Z'),
      amount: -30.0,
      dueDay: 3,
      isPaid: true,
      isOverdue: false,
      user_id: userId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      avatar: '/assets/avatars/elevate-education.jpg',
      name: 'Elevate Education',
      category: 'Education',
      date: new Date('2024-07-05T11:15:22Z'),
      amount: -50.0,
      dueDay: 5,
      isPaid: true,
      isOverdue: false,
      user_id: userId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      avatar: '/assets/avatars/swift-ride-share.jpg',
      name: 'Swift Ride Share',
      category: 'Transportation',
      date: new Date('2024-08-07T10:00:00Z'),
      amount: -25.99,
      dueDay: 7,
      isPaid: true,
      isOverdue: false,
      user_id: userId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      avatar: '/assets/avatars/technova-innovations.jpg',
      name: 'TechNova Innovations',
      category: 'Technology',
      date: new Date('2024-08-10T14:30:00Z'),
      amount: -79.99,
      dueDay: 10,
      isPaid: true,
      isOverdue: false,
      user_id: userId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      avatar: '/assets/avatars/green-plate-eatery.jpg',
      name: 'Green Plate Eatery Subscription',
      category: 'Dining Out',
      date: new Date('2024-08-05T12:00:00Z'),
      amount: -45.5,
      dueDay: 5,
      isPaid: true,
      isOverdue: false,
      user_id: userId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      avatar: '/assets/avatars/buzz-marketing-group.jpg',
      name: 'Buzz Marketing Group',
      category: 'Business',
      date: new Date('2024-08-09T09:15:00Z'),
      amount: -120.0,
      dueDay: 9,
      isPaid: true,
      isOverdue: false,
      user_id: userId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      avatar: '/assets/icons/wifi.svg',
      name: 'CityConnect Broadband',
      category: 'Internet',
      date: new Date('2024-08-14T08:30:00Z'),
      amount: -55.0,
      dueDay: 14,
      isPaid: true,
      isOverdue: false,
      user_id: userId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      avatar: '/assets/icons/bank.svg',
      name: 'Mortgage Payment',
      category: 'Housing',
      date: new Date('2024-08-01T00:00:00Z'),
      amount: -875.0,
      dueDay: 1,
      isPaid: true,
      isOverdue: false,
      user_id: userId,
      created_at: new Date(),
      updated_at: new Date(),
    },
  ])
}
