services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:3000'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PORT=3000
      - NODE_ENV=${NODE_ENV:-development}
      - DB_USER=${DB_USER:-finance}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-finance}
      - DATABASE_URL=postgres://${DB_USER:-finance}:${DB_PASSWORD}@postgres:${DB_PORT:-5432}/${DB_NAME:-finance}
      - SESSION_SECRET=${SESSION_SECRET}
    volumes:
      - ./:/app
      - /app/node_modules

  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USER:-finance}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME:-finance}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-postgres-processed.sql:/docker-entrypoint-initdb.d/init-postgres.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER:-finance}']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
