services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6000:6000'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PORT=6000
      - NODE_ENV=production
      - DB_USER=${DB_USER:?DB_USER is required}
      - DB_PASSWORD=${DB_PASSWORD:?DB_PASSWORD is required}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:?DB_NAME is required}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      - SESSION_SECRET=${SESSION_SECRET:?SESSION_SECRET is required}
      - DEMO_USER_ID=${DEMO_USER_ID:?DEMO_USER_ID is required}
      - DEMO_PASSWORD_HASH=${DEMO_PASSWORD_HASH:?DEMO_PASSWORD_HASH is required}
    volumes:
      - ./app:/app/app
      - ./db:/app/db
      - ./public:/app/public
      - ./scripts:/app/scripts
      - /app/node_modules
      - ./app/lib/data.json:/app/public/data.json
      - ./scripts/docker-entrypoint-prod.sh:/docker-entrypoint.sh
    entrypoint: ['/docker-entrypoint.sh']

  postgres:
    image: postgres:15
    ports:
      - '6432:5432'
    environment:
      - POSTGRES_USER=${DB_USER:?DB_USER is required}
      - POSTGRES_PASSWORD=${DB_PASSWORD:?DB_PASSWORD is required}
      - POSTGRES_DB=${DB_NAME:?DB_NAME is required}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-postgres-processed.sql:/docker-entrypoint-initdb.d/init-postgres.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER}']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
